### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by brauliobo** [randym/axlsx#419] opened 2015-09-29 22:45 UTC
The stable version released is quite old and it depends on the old rubyzip (1.0) that conflicts with other packages using newer rubyzip versions.

**Comment by toncid** [comment] 2015-11-04 12:08
+1

Rubyzip incompatibility is problematic.

**Comment by kamalptw** [comment] 2015-11-10 11:05
+1
Rubyzip incompatibility is a big issue

**Comment by swatosh** [comment] 2015-12-29 01:01
2.1.0.pre has been on rubygems.org for nine months, any progress on moving to 2.1.0 final?

**Comment by severinedarlot** [comment] 2016-01-29 09:53
+1

**Comment by stevendaniels** [comment] 2016-02-02 11:14
Hi. I'm one of the maintainers or Roo. One of our users mentioned that the rubygems version of Axlsx doesn't incompatible with current versions of Roo (because of rubyzip). Your master branch is compatible, though. 

SEE: https://github.com/roo-rb/roo/issues/296

**Comment by randym** [comment] 2016-02-02 11:41
Please use master for now.
I 100% agree that we need a release. There are two things blocking:

1. Testing Environment. 
Anyone want to sponsor a windows box/VM with licences for the versions of Excel the community would like to see supported?

2. Time - rubyzip aside, and even with all the spec coverage, manual regression testing is something that should happen before an official release. Looking at some recent issues there are likely problems with default chart background colours and possibly comments in recent versions of excel.

**Comment by brauliobo** [comment] 2016-05-17 20:57
Maybe realesing version 2.0.2 is easier?

**Comment by brauliobo** [comment] 2016-05-17 20:59
Also another experieced developer could help doing the changes and releasing

**Comment by randym** [comment] 2017-04-01 09:55
Closing this issue. Release will be handled in #501

**Closed by randym** 2017-04-01 09:55 UTC
