### ISSUE TITLE
Request for gem release

### ISSUE THREAD

**Issue by johnnyshields** [randym/axlsx#370] opened 2015-01-03 19:16 UTC
Looks like it's been over a year. In particular am wanting to update RubyZip dependency.

**Comment by jurriaan** [comment] 2015-01-03 19:22
Duplicate of #328

@randym can you add me as gem owner so I can push out a new version?

**Comment by rhomeister** [comment] 2015-02-14 20:46
+1 Also getting stuck with RubyZip dependency

**Comment by alankessler** [comment] 2015-03-10 18:53
@jurriaan ... Please Fork this project, @randym seems to be MIA.

**Comment by jurriaan** [comment] 2015-03-14 15:27
I've just released a pre-release version. (v2.1.0.pre)
Please test it and report if you have any problems

**Closed** 2015-04-27 15:02 UTC

**Comment by swatosh** [comment] 2015-07-22 05:38
Any reports of issues with the pre-release? Is it time to push a new
release?

Thanks!
--
Joe
